[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pymodaq-plugins-spectraphysics"
dynamic = ["version"]
description = "Set of PyMoDAQ plugins for devices from SpectraPhysics"
readme = "README.rst"
requires-python = ">=3.9"
license = "MIT"
keywords = ["PyMoDAQ", "plugin", "instrument", "MaiTai"]
authors = [
{ name = "Brian Squires", email = "Brian.Squires@unt.edu" },
]
classifiers = [
"Development Status :: 4 - Beta",
"Programming Language :: Python :: 3",
"Programming Language :: Python :: 3.9",
"Programming Language :: Python :: 3.10",
"Programming Language :: Python :: 3.11",
"License :: OSI Approved :: MIT License",
"Operating System :: OS Independent",
]
dependencies = [
"pymodaq>=5.0.18",
"pyserial",
]

[project.urls]
Homepage = "https://www.google.com/search?q=https://github.com/your-github/pymodaq_plugins_spectraphysics"
"Bug Tracker" = "https://www.google.com/search?q=https://github.com/your-github/pymodaq_plugins_spectraphysics/issues"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0"

[tool.hatch.build.targets.wheel.sources]
"src/pymodaq_plugins_spectraphysics" = "pymodaq_plugins_spectraphysics"

[project.entry-points."pymodaq.plugins"]
SpectraPhysics = "pymodaq_plugins_spectraphysics"

[project.entry-points."pymodaq.instruments"]
MaiTai = "pymodaq_plugins_spectraphysics.daq_move_plugins.daq_move_MaiTai:DAQ_Move_MaiTai"